// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp2hye965_9bSJAAoNxXL1bOg2TEjleM4',
    appId: '1:170736238948:web:2542afff1c75cdfee67a71',
    messagingSenderId: '170736238948',
    projectId: 'cluro10',
    authDomain: 'cluro10.firebaseapp.com',
    storageBucket: 'cluro10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ZSWMQjSZYUjS5ZSbryjtU-uCiMDy1hk',
    appId: '1:170736238948:android:acdbd61ffcb3d4dbe67a71',
    messagingSenderId: '170736238948',
    projectId: 'cluro10',
    storageBucket: 'cluro10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArR8dqSDSW6rOmF4d62UUaLTC2m67KJHM',
    appId: '1:170736238948:ios:36cd7538690d8771e67a71',
    messagingSenderId: '170736238948',
    projectId: 'cluro10',
    storageBucket: 'cluro10.firebasestorage.app',
    iosBundleId: 'com.example.cluroAiHrms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArR8dqSDSW6rOmF4d62UUaLTC2m67KJHM',
    appId: '1:170736238948:ios:36cd7538690d8771e67a71',
    messagingSenderId: '170736238948',
    projectId: 'cluro10',
    storageBucket: 'cluro10.firebasestorage.app',
    iosBundleId: 'com.example.cluroAiHrms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp2hye965_9bSJAAoNxXL1bOg2TEjleM4',
    appId: '1:170736238948:web:68e9e31c580f8581e67a71',
    messagingSenderId: '170736238948',
    projectId: 'cluro10',
    authDomain: 'cluro10.firebaseapp.com',
    storageBucket: 'cluro10.firebasestorage.app',
  );
}
